# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Jakub Kubacki]

In [3]:
import numpy as np

Krok 1 — Dane

In [4]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],
[49.99, 52.99, 47.99],
[14.99, 15.99, 13.99],
# Produkt A
# Produkt B
# Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


Krok 2 — Zadania

In [ ]:
# Broadcasting: macierz (4×3) * skalar
ceny_brutto = ceny * 1.05
print(ceny_brutto)

[[ 36.8877  39.3477  35.6577]
 [ 61.4877  65.1777  59.0277]
 [ 18.4377  19.6677  17.2077]
 [122.9877 129.1377 116.8377]]


In [ ]:
rabaty = np.array([0.10, 0.05, 0.15])
# Broadcasting: macierz (4×3) * wektor (3,)
ceny_rabat = ceny - rabaty
print(ceny_rabat)

[[ 29.89  31.94  28.84]
 [ 49.89  52.94  47.84]
 [ 14.89  15.94  13.84]
 [ 99.89 104.94  94.84]]


In [ ]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
# Broadcasting: macierz (4×3) * wektor kolumnowy (4×1)
koszt_zakupu = ceny / (1 + marza)
print(koszt_zakupu)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [5]:
# Podpowiedź: użyj .argmin(axis=1) i listy sklepów
najtansze_indeksy = ceny.argmin(axis=1)
for i, index in enumerate(najtansze_indeksy):
    print(f"Produkt {produkty[i]}: Najtańszy sklep to {sklepy[index]} ({ceny[i, index]})")


Produkt A: Najtańszy sklep to Online (28.99)
Produkt B: Najtańszy sklep to Online (47.99)
Produkt C: Najtańszy sklep to Online (13.99)
Produkt D: Najtańszy sklep to Online (94.99)
