# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Jakub Kubacki]

In [1]:
import numpy as np

Krok 1 — Dane

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],
[49.99, 52.99, 47.99],
[14.99, 15.99, 13.99],
# Produkt A
# Produkt B
# Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


Krok 2 — Zadania

In [3]:
# Broadcasting: macierz (4×3) * skalar
ceny_brutto = ceny * 1.05
print(ceny_brutto)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [4]:
rabaty = np.array([0.10, 0.05, 0.15])
# Broadcasting: macierz (4×3) * wektor (3,)
ceny_rabat = ceny - rabaty
print(ceny_rabat)

[[ 29.89  31.94  28.84]
 [ 49.89  52.94  47.84]
 [ 14.89  15.94  13.84]
 [ 99.89 104.94  94.84]]


In [5]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
# Broadcasting: macierz (4×3) * wektor kolumnowy (4×1)
koszt_zakupu = ceny / (1 + marza)
print(koszt_zakupu)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [6]:
# Podpowiedź: użyj .argmin(axis=1) i listy sklepów
najtansze_indeksy = ceny.argmin(axis=1)
for i, index in enumerate(najtansze_indeksy):
    print(f"Produkt {produkty[i]}: Najtańszy sklep to {sklepy[index]} ({ceny[i, index]})")


Produkt A: Najtańszy sklep to Online (28.99)
Produkt B: Najtańszy sklep to Online (47.99)
Produkt C: Najtańszy sklep to Online (13.99)
Produkt D: Najtańszy sklep to Online (94.99)


Zadanie 2a — Reshape

In [10]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking

In [8]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne (samodzielnie)

In [ ]:
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące
# 1. Reshape na macierz 6×2
macierz = sprzedaz_flat.reshape(6, 2)
zmiana = macierz[:, 1] - macierz[:, 0]
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1- kolumna 0)
print(f"Reshape:\n{macierz}")
print(f"Średnia sprzedaż: {macierz.mean(axis=1)}")
print(f"Zmiana (miesiąc 2 - miesiąc 1): {zmiana}")

Reshape:
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia sprzedaż: [150. 225. 215. 170. 240. 225.]
Zmiana (miesiąc 2 - miesiąc 1): [100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [ ]:
# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()

wektor = kwartaly.flatten()

wektor_13 = np.concatenate([wektor, np.array([235])])

print("Flatten:", wektor)
print("Po dodaniu 13. miesiąca:", wektor_13)
print("Długość:", len(wektor_13))

Flatten: [120 135  98 142 167 189 201 178 156 143 198 221]
Po dodaniu 13. miesiąca: [120 135  98 142 167 189 201 178 156 143 198 221 235]
Długość: 13


Ćwiczenie 3: Analiza danych finansowych (30 min)

Dane

In [12]:
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadanie 3a: Analiza wynagrodzeń

In [ ]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
srednia_p = pensje.mean()
mediana_p = np.median(pensje)
odchylenie_p = pensje.std()
print(f"Średnia: {srednia_p}, Mediana: {mediana_p}, Odchylenie: {odchylenie_p:.2f}")
# 2. Wyświetl imiona osób zarabiających powyżej średniej

pracownicy = np.array(pracownicy)
print("Powyżej średniej:", pracownicy[pensje > srednia_p])

# 3. Wyświetl imiona osób zarabiających poniżej mediany
print("Poniżej mediany:", pracownicy[pensje < mediana_p])
# 4. Oblicz rozstęp (max- min) i rozstęp międzykwartylowy (IQR)

rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"Rozstęp: {rozstep}, IQR: {iqr}")

Średnia: 6425.0, Mediana: 6050.0, Odchylenie: 1616.90
Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900, IQR: 2200.0


Zadanie 3b: System premii (np.where)

In [ ]:
# Zasady premii:
#- ocena >= 4.5 → premia 2000 zł
#- ocena >= 4.0 → premia 1000 zł
#- ocena < 4.0 → premia 0 zł

# Oblicz nowe wynagrodzenie (pensja + premia)
# Kto dostał najwyższą premię? Użyj argmax()
# Obliczanie premii
premie = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))

nowe_wynagrodzenie = pensje + premie
kto_max_premia = pracownicy[np.argmax(premie)]

print(f"Najwyższą premię dostał/a: {kto_max_premia}")

Najwyższą premię dostał/a: Ewa


Zadanie 3c: Ranking (argsort)

In [ ]:
# Posortuj pracowników wg pensji (od najwyższej)
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]
# Wyświetl ranking: pozycja, imię, pensja, staż

kolejnosc = np.argsort(pensje)[::-1] # [::-1] odwraca tablicę, by mieć malejąco

print("\nRANKING PRACOWNIKÓW:")
for i, idx in enumerate(kolejnosc, 1):
    print(f"{i}. {pracownicy[idx]:6} | Pensja: {pensje[idx]} zł | Staż: {staz[idx]} lat")


RANKING PRACOWNIKÓW:
1. Marek  | Pensja: 9100 zł | Staż: 15 lat
2. Zofia  | Pensja: 8500 zł | Staż: 12 lat
3. Jan    | Pensja: 7200 zł | Staż: 8 lat
4. Kasia  | Pensja: 6300 zł | Staż: 5 lat
5. Tomek  | Pensja: 5800 zł | Staż: 4 lat
6. Anna   | Pensja: 5500 zł | Staż: 3 lat
7. Ewa    | Pensja: 4800 zł | Staż: 2 lat
8. Piotr  | Pensja: 4200 zł | Staż: 1 lat


Zadanie 3d: Korelacja

In [ ]:
# Oblicz korelację: staż vs pensja
# Oblicz korelację: staż vs ocena
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)
kor_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
kor_staz_ocena = np.corrcoef(staz, oceny)[0, 1]

print(f"\nKorelacja Staż-Pensja: {kor_staz_pensja:.2f}")
print(f"Korelacja Staż-Ocena: {kor_staz_ocena:.2f}")


Korelacja Staż-Pensja: 0.99
Korelacja Staż-Ocena: 0.04


Zadanie 3e: Analiza sprzedaży (broadcasting)

In [22]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

# Najlepszy produkt (suma po wierszach - axis=1)
najlepszy_produkt_idx = np.argmax(przychod.sum(axis=1))
print(f"Najlepszy produkt: {produkty_nazwy[najlepszy_produkt_idx]}")

# Najlepszy miesiąc (suma po kolumnach - axis=0)
najlepszy_miesiac_idx = np.argmax(przychod.sum(axis=0))
print(f"Najlepszy miesiąc (indeks): {najlepszy_miesiac_idx}")

# Trend
trend_poczatek = przychod[:, :3].sum()
trend_koniec = przychod[:, 3:].sum()
print(f"Przychód I-III: {trend_poczatek}, Przychód IV-VI: {trend_koniec}")

Najlepszy produkt: Smartfon
Najlepszy miesiąc (indeks): 1
Przychód I-III: 2463950, Przychód IV-VI: 2536500


Ćwiczenie 4: Generowanie danych (15 min)
Krok 1 — Generowanie

In [ ]:
# Wygeneruj dane o 100 klientach sklepu:
#- wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
#- wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
#- liczba_wizyt: rozkład Poissona, lambda=5
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

Krok 2 — Analiza (samodzielnie)

In [ ]:
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)

print(f"\nWydatki - Średnia: {wydatki.mean():.2f}, Mediana: {np.median(wydatki):.2f}")
# 2. Korelacja wiek vs wydatki

# 3. Korelacja wizyty vs wydatki
kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print(f"Korelacja Wiek-Wydatki: {kor_wiek_wydatki:.2f}")
print(f"Korelacja Wizyty-Wydatki: {kor_wizyty_wydatki:.2f}")
# 4. Segmentacja klientów za pomocą np.where:
#- "WYSOKI" gdy wydatki > średnia + std
#
#- "NISKI" gdy wydatki < średnia- std- "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
# sr = wydatki.mean()
# sd = wydatki.std()
# segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr- sd, 'NISKI', 'ŚREDNI'))
sr = wydatki.mean()
sd = wydatki.std()

segmenty = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))
# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)
etykiety, ilosc = np.unique(segmenty, return_counts=True)
print("\nLiczba klientów w segmentach:")
for et, il in zip(etykiety, ilosc):
    print(f"{et}: {il}")


Wydatki - Średnia: 523.23, Mediana: 529.67
Korelacja Wiek-Wydatki: -0.05
Korelacja Wizyty-Wydatki: -0.03

Liczba klientów w segmentach:
NISKI: 16
WYSOKI: 14
ŚREDNI: 70
