# Laboratorium 3 — NumPy
**Autor:** [Jakub Kubacki]

In [1]:
import numpy as np

In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [10]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])


Zadania

In [15]:
#1. Sprzedaż w styczniu (indeks 0):
print(miesiace_sprzedaz[0])

120


In [16]:
#2
print(miesiace_sprzedaz[-1])

221


In [19]:
#3
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [24]:
#4
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [25]:
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [26]:
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [28]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [31]:
dane[0,1]

np.int64(145)

In [32]:
dane[2]

array([234, 267, 289])

In [34]:
dane[: ,0]

array([120,  89, 234,  56])

In [36]:
dane[1:3, 1:3]

array([[102,  95],
       [267, 289]])

Dane

In [37]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [48]:
# Średnia cena, najdroższy produkt, najtańszy produkt
srednia_cena = ceny.mean()
print(srednia_cena)

1171.0


In [49]:
najdrosza_cena = ceny.max()
print(najdrosza_cena)

3499


In [50]:
najnizsza_cena = ceny.min()
print(najnizsza_cena)

89


In [52]:
# Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu
wartosci_produktow = ceny * ilosci_magazyn
print(wartosci_produktow)

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]


In [53]:
calkowita_wartosc = wartosci_produktow.sum()
print(calkowita_wartosc)

549465


In [58]:
# Stworz array z cenami po rabacie 15% (promocja świąteczna)
ceny_promocja = ceny * 0.85
print(ceny_promocja)

[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]


In [59]:
# Stworz array z cenami po uwzględnieniu VAT 23%
ceny_brutto = ceny * 1.23
print(ceny_brutto)

[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]


In [60]:
# Ile produktów kosztuje powyżej 1000 zł?
liczba_drogich = (ceny > 1000).sum()
print(liczba_drogich)

4


In [61]:
# Konwersja listy nazw na array, aby móc używać masek
nazwy_arr = np.array(nazwy)

In [65]:
# Produkty z wysoką oceną (>= 4.5)
maska_oceny = oceny_klientow >= 4.5
print("Produkty premium (ocena >= 4.5):")
print(nazwy_arr[maska_oceny], ceny[maska_oceny])

Produkty premium (ocena >= 4.5):
['Laptop' 'Smartfon' 'Słuchawki' 'Monitor'] [3499 2499  349 1499]


In [66]:
# Produkty budżetowe (< 200 zł)
maska_tanie = ceny < 200
print("\nProdukty budżetowe (< 200 zł) - nazwy i stan:")
print(nazwy_arr[maska_tanie], ilosci_magazyn[maska_tanie])


Produkty budżetowe (< 200 zł) - nazwy i stan:
['Ładowarka' 'Mysz'] [312 201]


In [71]:
niski_stan = ilosci_magazyn < 30
produkty_do_zamowienia = nazwy_arr[niski_stan]
print(produkty_do_zamowienia)

['Laptop' 'Monitor']


In [73]:
wartosc_niskich_stanow = wartosci_produktow[niski_stan].sum()
print(wartosc_niskich_stanow)

86962


In [74]:
procent_wartosci = (wartosc_niskich_stanow / calkowita_wartosc) * 100
print(procent_wartosci)

15.826667758637946


In [76]:
import time
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [77]:
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 81.4 ms
NumPy: 6.2 ms
NumPy jest 13× szybszy!


In [78]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 14.8 ms
NumPy: 2.6 ms
NumPy jest 6× szybszy!


In [79]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 48.7 ms
NumPy: 4.3 ms
NumPy jest 11× szybszy!


## Wnioski z benchmarku- NumPy jest **...×** szybszy w mnożeniu
6
- NumPy jest **6×** szybszy w sumowaniu
- NumPy jest **11×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list